### ISSUE TITLE
error with apt ket ininstall_ros_melodic.sh

### ISSUE THREAD

**Issue by dfarning** [ROBOTIS-GIT/robotis_tools#4]
I just wanted to let you know that there is a problem with the apt key installed on line 35 of install_ros_melodic.sh . That key is incorrect. As a result the repo doesn't load correctly.

The command to install the correct key is on the ros wiki at http://wiki.ros.org/melodic/Installation/Ubuntu is

sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

**Comment by robotpilot** [comment]
@dfarning @dscroft 
Thank you very much. I have modified the key part as you have been informed.

**Comment by dfarning** [comment]
Thanks

I just got my TurtleBot3 this morning and am attempting a melodic on Ubuntu 18.04 install on both the TurtleBot and the host computer. I'll let you know if I come across any other issues.

David
